version: "3"

services:
  serv:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - "./app:/app"
      - "./figs:/figs"
    command: python3 serv.py
    environment:
        - TOKEN=hogehoge
